name: Release
on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Recreate discord token file
        run: |
          echo export const DISCORD_TOKEN=\"${{ secrets.DISCORD_TOKEN }}\" >> ./src/api/discordBotToken.ts
        shell: bash

      - name: Debug discord token file
        run: head -c -30 ./src/api/discordBotToken.ts
        shell: bash

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: npm run publish
